name: lzstring
version: 1.0.2+1
description: Dart implementation of lz-string compression algorithm. Originally written in JavaScript, for more details, please refer to http://pieroxy.net/blog/pages/lz-string/index.html
homepage: https://github.com/skipness/lzstring-dart
environment:
  sdk: '>=2.1.0 <3.0.0'
dependencies:
  typed_data: '^1.0.0'
dev_dependencies:
  test: ^1.0.0
